[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
aiohttp = "^3.9.5"
