
[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
Sphinx = "^7.3.7"
myst-parser = "^3.0.1"
furo = "^2024.5.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
